import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { ChevronRight, Target, Brain, Users, TrendingUp } from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Plans",
    desc: "Personalized workout and diet plans generated by AI based on your goals and body stats.",
  },
  {
    icon: Target,
    title: "Daily Tracking",
    desc: "Log progress, meals, and reps every day. Stay accountable to your trainer and yourself.",
  },
  {
    icon: Users,
    title: "Trainer Network",
    desc: "Elite trainers manage your entire journey — from onboarding to peak performance.",
  },
  {
    icon: TrendingUp,
    title: "Analytics & Insights",
    desc: "Visual dashboards and AI feedback that turn raw data into actionable coaching.",
  },
];

export default function Landing() {
  return (
    <div
      style={{ background: "#0A0A0A", minHeight: "100vh", overflowX: "hidden" }}
    >
      {/* Nav */}
      <nav
        className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-8 h-16"
        style={{
          background: "rgba(10,10,10,0.9)",
          backdropFilter: "blur(12px)",
          borderBottom: "1px solid rgba(255,255,255,0.05)",
        }}
      >
        <div className="flex items-center gap-2">
          <img
            src="/Fitness Icon.png"
            alt="TrackFit Logo"
            className="w-15 h-10 object-contain"
          />
          <span className="font-display text-xl tracking-widest text-white">
            TRACKFIT
          </span>
        </div>
        <div className="flex items-center gap-3">
          <Link to="/login" className="btn-ghost text-sm py-2 px-4">
            Login
          </Link>
          <Link to="/register" className="btn-primary text-sm py-2 px-4">
            Get Started
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative flex flex-col items-center justify-center min-h-screen text-center px-6 pt-16">
        {/* Background grid */}
        <div className="absolute inset-0 overflow-hidden">
          {/* Background image */}
          <div
            style={{
              position: "absolute",
              inset: 0,
              backgroundImage: "url(/Background.jfif)",
              backgroundSize: "cover",
              backgroundPosition: "center",
              backgroundAttachment: "fixed",
              opacity: 1,
            }}
          />
          {/* Overlay for text readability */}
          <div
            style={{
              position: "absolute",
              inset: 0,
              background: "rgba(20, 10, 10, 0.6)",
            }}
          />
          <div
            style={{
              position: "absolute",
              inset: 0,
              backgroundImage:
                "linear-gradient(rgba(255,60,47,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(255,60,47,0.03) 1px, transparent 1px)",
              backgroundSize: "60px 60px",
            }}
          />
          <div
            style={{
              position: "absolute",
              top: "20%",
              left: "50%",
              transform: "translateX(-50%)",
              width: "600px",
              height: "600px",
              borderRadius: "50%",
              background:
                "radial-gradient(circle, rgba(255,60,47,0.12) 0%, transparent 70%)",
              filter: "blur(40px)",
            }}
          />
        </div>

        <div className="relative z-10 max-w-5xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          ></motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.1 }}
            className="font-display text-white leading-none mb-6"
            style={{
              fontSize: "clamp(72px, 12vw, 160px)",
              lineHeight: 0.9,
              letterSpacing: "-0.02em",
            }}
          >
            TRAIN
            <br />
            <span
              style={{
                color: "var(--accent)",
                WebkitTextStroke: "2px var(--accent)",
                WebkitTextFillColor: "transparent",
              }}
            >
              SMARTER
            </span>
            <br />
            WIN MORE
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="text-lg mb-10 max-w-xl mx-auto"
            style={{ color: "var(--text-secondary)", lineHeight: 1.7 }}
          >
            The elite fitness platform connecting trainers and athletes.
            AI-generated plans, real-time tracking, and intelligent feedback —
            all in one place.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
            className="flex flex-col sm:flex-row gap-4 justify-center"
          >
            <Link
              to="/register"
              className="btn-primary inline-flex items-center gap-2 py-4 px-8 text-base"
              style={{ borderRadius: 0 }}
            >
              Start Training Free
              <ChevronRight size={18} />
            </Link>
            <Link
              to="/login"
              className="btn-ghost inline-flex items-center gap-2 py-4 px-8 text-base"
              style={{ borderRadius: 0 }}
            >
              Sign In
            </Link>
          </motion.div>

          {/* Stats row */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.8 }}
            className="flex items-center justify-center gap-12 mt-16 pt-10 border-t"
            style={{ borderColor: "rgba(255,255,255,0.07)" }}
          >
            {[
              ["2,400+", "Athletes"],
              ["340+", "Elite Trainers"],
              ["98%", "Goal Achievement"],
            ].map(([val, label]) => (
              <div key={label} className="text-center">
                <p
                  className="font-display text-3xl"
                  style={{ color: "var(--accent)" }}
                >
                  {val}
                </p>
                <p
                  className="text-xs font-heading tracking-widest uppercase mt-1"
                  style={{ color: "var(--text-secondary)" }}
                >
                  {label}
                </p>
              </div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section className="py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <p
              className="font-heading text-xs tracking-widest uppercase mb-4"
              style={{ color: "var(--accent)" }}
            >
              Platform Features
            </p>
            <h2
              className="font-display text-white"
              style={{ fontSize: "clamp(40px, 6vw, 80px)", lineHeight: 1 }}
            >
              BUILT FOR
              <br />
              PERFORMANCE
            </h2>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {features.map(({ icon: Icon, title, desc }, i) => (
              <motion.div
                key={title}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="p-8 rounded card-hover"
                style={{
                  background: "var(--bg-muted)",
                  border: "1px solid rgba(255,255,255,0.06)",
                }}
              >
                <div className="flex items-center gap-4 mb-4">
                  <div
                    className="w-10 h-10 flex items-center justify-center"
                    style={{ background: "rgba(255,60,47,0.1)" }}
                  >
                    <Icon size={20} style={{ color: "var(--accent)" }} />
                  </div>
                  <h3 className="font-heading font-semibold text-lg uppercase tracking-wide text-white">
                    {title}
                  </h3>
                </div>
                <p style={{ color: "var(--text-secondary)", lineHeight: 1.7 }}>
                  {desc}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section
        className="py-20 px-6 diagonal-cut"
        style={{ background: "var(--accent)", marginTop: "4rem" }}
      >
        <div className="max-w-3xl mx-auto text-center">
          <h2
            className="font-display text-white mb-6"
            style={{ fontSize: "clamp(40px, 6vw, 80px)" }}
          >
            READY TO
            <br />
            DOMINATE?
          </h2>
          <Link
            to="/register"
            className="inline-flex items-center gap-2 px-10 py-4 bg-black text-white font-heading font-semibold tracking-widest uppercase text-sm transition-transform hover:scale-105"
          >
            Join TrackFit Now <ChevronRight size={16} />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer
        className="py-8 px-8 text-center border-t"
        style={{ borderColor: "rgba(255,255,255,0.06)" }}
      >
        <p className="text-xs" style={{ color: "var(--text-secondary)" }}>
          © 2025 TrackFit. Built for elite performance.
        </p>
      </footer>
    </div>
  );
}
